[package]
name = "encoding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "encoding"
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.18.0"
pyo3 = "0.18.3"
rand = "0.8.5"
